// Auto-generated by scripts/fetch-data.ts
// Generated at: 2026-06-17T11:58:05.793Z

import { GroupTable } from '@/types';

export const GENERATED_STANDINGS: GroupTable[] = [
  {
    "groupId": "J",
    "name": "Group J",
    "teams": [
      {
        "position": 1,
        "teamId": "t-aut",
        "teamName": "Austria",
        "teamFlag": "🇦🇹",
        "played": 1,
        "won": 1,
        "drawn": 0,
        "lost": 0,
        "goalsFor": 3,
        "goalsAgainst": 1,
        "goalDifference": 2,
        "points": 3
      },
      {
        "position": 2,
        "teamId": "t-jor",
        "teamName": "Jordan",
        "teamFlag": "🇯🇴",
        "played": 1,
        "won": 0,
        "drawn": 0,
        "lost": 1,
        "goalsFor": 1,
        "goalsAgainst": 3,
        "goalDifference": -2,
        "points": 0
      }
    ]
  }
] as const;
