// Auto-generated by scripts/fetch-data.ts
// Generated at: 2026-06-17T11:58:05.776Z
// Source: ESPN API (https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard)

import { Match } from '@/types';

export const GENERATED_MATCHES: Match[] = [
  {
    "id": "espn-760431",
    "matchdayId": "md-1",
    "matchdayName": "Matchday 1",
    "homeTeam": {
      "id": "t-aut",
      "name": "Austria",
      "shortName": "AUT",
      "flag": "🇦🇹",
      "group": "J",
      "color": "#d72b2c",
      "secondaryColor": "#000000"
    },
    "awayTeam": {
      "id": "t-jor",
      "name": "Jordan",
      "shortName": "JOR",
      "flag": "🇯🇴",
      "group": "J",
      "color": "#E70000",
      "secondaryColor": "#ffffff"
    },
    "score": {
      "home": 3,
      "away": 1
    },
    "status": "FT",
    "minute": null,
    "startTime": "2026-06-17T04:00Z",
    "venue": "Levi's Stadium",
    "isFavorite": false,
    "events": [
      {
        "id": "ge-760431-0",
        "type": "GOAL",
        "minute": 20,
        "player": "Romano Schmid",
        "team": "home"
      },
      {
        "id": "ge-760431-1",
        "type": "GOAL",
        "minute": 49,
        "player": "Ali Olwan",
        "team": "away"
      },
      {
        "id": "ge-760431-2",
        "type": "OWN_GOAL",
        "minute": 75,
        "player": "Yazan Al-Arab",
        "team": "home",
        "description": "Own Goal by Yazan Al-Arab"
      },
      {
        "id": "ge-760431-3",
        "type": "YELLOW_CARD",
        "minute": 76,
        "player": "Marcel Sabitzer",
        "team": "home"
      },
      {
        "id": "ge-760431-4",
        "type": "PENALTY",
        "minute": 90,
        "player": "Marko Arnautovic",
        "team": "home"
      }
    ],
    "stats": {
      "possession": {
        "home": 63,
        "away": 36
      },
      "shots": {
        "home": 11,
        "away": 11
      },
      "shotsOnTarget": {
        "home": 4,
        "away": 4
      },
      "corners": {
        "home": 4,
        "away": 3
      },
      "fouls": {
        "home": 12,
        "away": 7
      },
      "yellowCards": {
        "home": 0,
        "away": 0
      },
      "redCards": {
        "home": 0,
        "away": 0
      },
      "offsides": {
        "home": 0,
        "away": 0
      }
    },
    "lineups": {
      "home": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      },
      "away": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      }
    }
  },
  {
    "id": "espn-760435",
    "matchdayId": "md-1",
    "matchdayName": "Matchday 1",
    "homeTeam": {
      "id": "t-por",
      "name": "Portugal",
      "shortName": "POR",
      "flag": "🇵🇹",
      "group": "K",
      "color": "#da291c",
      "secondaryColor": "#0D6938"
    },
    "awayTeam": {
      "id": "t-cod",
      "name": "Congo DR",
      "shortName": "COD",
      "flag": "🇨🇩",
      "group": "K",
      "color": "#418fde",
      "secondaryColor": "#C60000"
    },
    "score": {
      "home": 0,
      "away": 0
    },
    "status": "SCHEDULED",
    "minute": null,
    "startTime": "2026-06-17T17:00Z",
    "venue": "NRG Stadium",
    "isFavorite": false,
    "events": [],
    "stats": {
      "possession": {
        "home": 0,
        "away": 0
      },
      "shots": {
        "home": 0,
        "away": 0
      },
      "shotsOnTarget": {
        "home": 0,
        "away": 0
      },
      "corners": {
        "home": 0,
        "away": 0
      },
      "fouls": {
        "home": 0,
        "away": 0
      },
      "yellowCards": {
        "home": 0,
        "away": 0
      },
      "redCards": {
        "home": 0,
        "away": 0
      },
      "offsides": {
        "home": 0,
        "away": 0
      }
    },
    "lineups": {
      "home": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      },
      "away": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      }
    }
  },
  {
    "id": "espn-760437",
    "matchdayId": "md-1",
    "matchdayName": "Matchday 1",
    "homeTeam": {
      "id": "t-eng",
      "name": "England",
      "shortName": "ENG",
      "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
      "group": "L",
      "color": "#ffffff",
      "secondaryColor": "#EA1F29"
    },
    "awayTeam": {
      "id": "t-cro",
      "name": "Croatia",
      "shortName": "CRO",
      "flag": "🇭🇷",
      "group": "L",
      "color": "#ff0000",
      "secondaryColor": "#0c2fff"
    },
    "score": {
      "home": 0,
      "away": 0
    },
    "status": "SCHEDULED",
    "minute": null,
    "startTime": "2026-06-17T20:00Z",
    "venue": "AT&T Stadium",
    "isFavorite": false,
    "events": [],
    "stats": {
      "possession": {
        "home": 0,
        "away": 0
      },
      "shots": {
        "home": 0,
        "away": 0
      },
      "shotsOnTarget": {
        "home": 0,
        "away": 0
      },
      "corners": {
        "home": 0,
        "away": 0
      },
      "fouls": {
        "home": 0,
        "away": 0
      },
      "yellowCards": {
        "home": 0,
        "away": 0
      },
      "redCards": {
        "home": 0,
        "away": 0
      },
      "offsides": {
        "home": 0,
        "away": 0
      }
    },
    "lineups": {
      "home": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      },
      "away": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      }
    }
  },
  {
    "id": "espn-760434",
    "matchdayId": "md-1",
    "matchdayName": "Matchday 1",
    "homeTeam": {
      "id": "t-gha",
      "name": "Ghana",
      "shortName": "GHA",
      "flag": "🇬🇭",
      "group": "L",
      "color": "#fbd632",
      "secondaryColor": "#000000"
    },
    "awayTeam": {
      "id": "t-pan",
      "name": "Panama",
      "shortName": "PAN",
      "flag": "🇵🇦",
      "group": "L",
      "color": "#d21034",
      "secondaryColor": "#005293"
    },
    "score": {
      "home": 0,
      "away": 0
    },
    "status": "SCHEDULED",
    "minute": null,
    "startTime": "2026-06-17T23:00Z",
    "venue": "BMO Field",
    "isFavorite": false,
    "events": [],
    "stats": {
      "possession": {
        "home": 0,
        "away": 0
      },
      "shots": {
        "home": 0,
        "away": 0
      },
      "shotsOnTarget": {
        "home": 0,
        "away": 0
      },
      "corners": {
        "home": 0,
        "away": 0
      },
      "fouls": {
        "home": 0,
        "away": 0
      },
      "yellowCards": {
        "home": 0,
        "away": 0
      },
      "redCards": {
        "home": 0,
        "away": 0
      },
      "offsides": {
        "home": 0,
        "away": 0
      }
    },
    "lineups": {
      "home": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      },
      "away": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      }
    }
  },
  {
    "id": "espn-760436",
    "matchdayId": "md-1",
    "matchdayName": "Matchday 1",
    "homeTeam": {
      "id": "t-uzb",
      "name": "Uzbekistan",
      "shortName": "UZB",
      "flag": "🇺🇿",
      "group": "K",
      "color": "#ffffff",
      "secondaryColor": "#0072CE"
    },
    "awayTeam": {
      "id": "t-col",
      "name": "Colombia",
      "shortName": "COL",
      "flag": "🇨🇴",
      "group": "K",
      "color": "#fbd632",
      "secondaryColor": "#21418c"
    },
    "score": {
      "home": 0,
      "away": 0
    },
    "status": "SCHEDULED",
    "minute": null,
    "startTime": "2026-06-18T02:00Z",
    "venue": "Estadio Banorte",
    "isFavorite": false,
    "events": [],
    "stats": {
      "possession": {
        "home": 0,
        "away": 0
      },
      "shots": {
        "home": 0,
        "away": 0
      },
      "shotsOnTarget": {
        "home": 0,
        "away": 0
      },
      "corners": {
        "home": 0,
        "away": 0
      },
      "fouls": {
        "home": 0,
        "away": 0
      },
      "yellowCards": {
        "home": 0,
        "away": 0
      },
      "redCards": {
        "home": 0,
        "away": 0
      },
      "offsides": {
        "home": 0,
        "away": 0
      }
    },
    "lineups": {
      "home": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      },
      "away": {
        "formation": "N/A",
        "starting": [],
        "substitutes": []
      }
    }
  }
];
